### ISSUE TITLE
CNKI 报病毒

### ISSUE THREAD

**Issue by chzh20** [l0o0/translators_CN#9]
win10  defender 会报病毒。

**Comment by Lemmingh** [comment]
你那里报了什么威胁？

---

我这里没问题。

<https://github.com/l0o0/translators_CN/blob/71616dabc17bb3305c9b9268532846d1e0840c60/translators/CNKI.js>

```yaml
Name: CNKI.js
Size: 27621 bytes (26 KiB)
CRC32: 2D0324FE
CRC64: D15AFE86B4262322
SHA256: 6044BEF1E5A265A56415BF1BFA9DA5D8D7D5CEBF97BDE67065F7F69B066C9356
SHA1: 6B2A4DD1AAE0831222710EBE40D4632A9E945ACD
```

Windows Defender Antivirus

```yaml
Antimalware Client Version: 4.18.2007.8
Engine Version: 1.1.17300.4
Antivirus Version: 1.321.2085.0
Antispyware Version: 1.321.2085.0
Security Intelligence Version: 1.321.2085.0
```
